TicketingSystem/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using TicketingSystem.Models;

namespace TicketingSystem.Controllers {
    [Authorize(Roles ="ADMIN")]
    public class RolesController : Controller {
        private RoleManager<AppRole> _roleManager;
        private UserManager<AppUser> _userManager;

        public RolesController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager) {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Roles

        public async Task<IActionResult> Index() {
            return View(await _roleManager.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> DetailsAsync(string id) {
            if (id == null) {
                return View("NotFound");
            }
            var appRole = await _roleManager.Roles
                .FirstOrDefaultAsync(role => role.Id == id);
            if (appRole == null) {
                return View("NotFound");
            }
            return View(appRole);
        }

        // GET: Roles/Create
        public IActionResult Create() {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(AppRole appRole) {
            if (ModelState.IsValid) {
                IdentityResult result = await _roleManager.CreateAsync(new AppRole {
                    Name = appRole.Name,
                    IsActive = true,
                    CreateDate = DateTime.UtcNow,
                    UpdateDate = DateTime.UtcNow,
                    ConcurrencyStamp = HashCode.Combine(appRole.Name, DateTime.UtcNow).ToString()
                });
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                else {
                    ProcessErrors(result);
                }
            }
            return View(appRole);
        }


        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(string id) {
            if (id == null) {
                return View("NotFound");
            }

            var appRole = await _roleManager.FindByIdAsync(id);
            if (appRole == null) {
                return View("NotFound");
            }
            return View(appRole);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(string id, [Bind("IsActive,UpdateDate,Name")] AppRole appRole) {
        public async Task<IActionResult> EditAsync(string id, bool isActive, string concurrencyStamp) {
            AppRole appRole = await _roleManager.FindByIdAsync(id);
            if (appRole == null) {
                ModelState.AddModelError("", "Role not found.");
            }
            // else if (!AppRoleExists(appRole.Id)) {
            //     return View("NotFound");
            //     return NotFound();
            // }
            else if (!appRole.ConcurrencyStamp.Equals(concurrencyStamp)) {
                ModelState.AddModelError("", "Role has been changed by a different instance, go back and try again.");
            }
            else if (appRole.IsActive == isActive) {
                ModelState.AddModelError("", "Nothing has changed");
            }
            else {
                IdentityResult result;
                if (ModelState.IsValid) {
                    appRole.IsActive = isActive;
                    appRole.UpdateDate = DateTime.UtcNow;
                    result = await _roleManager.UpdateAsync(appRole);
                    if (!result.Succeeded) {
                        ProcessErrors(result);
                    }
                    return RedirectToAction("Index");
                }
            }
            return View(appRole);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(string id) {
            if (id == null) {
                return View("NotFound");
            }

            var appRole = await _roleManager.FindByIdAsync(id);
            if (appRole == null) {
                return View("NotFound");
            }

            return View(appRole);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id) {
            var appRole = await _roleManager.FindByIdAsync(id);
            if (appRole == null) {
                ModelState.AddModelError("", "Role not found.");
                return View(appRole);
            }
            else if (appRole.IsActive) {
                ModelState.AddModelError("", "Role is still active, deactivate the role first.");
                return View(appRole);
            }
            else if (await UsersInRoleExist(appRole.NormalizedName)) {
                ModelState.AddModelError("", "There are still users assigned to this role, re-assign them first.");
                return View(appRole);
            }
            else {
                IdentityResult result = await _roleManager.DeleteAsync(appRole);
                if (result.Succeeded) {
                    return RedirectToAction(nameof(Index));
                }
                else {
                    ProcessErrors(result);
                }
            }
            return View("Index", _roleManager.Roles);

        }

        private bool AppRoleExists(string id) {
            return _roleManager.Roles.Any(role => role.Id == id);
        }

        private void ProcessErrors(IdentityResult identityResult) {
            foreach (var error in identityResult.Errors) {
                ModelState.AddModelError("", error.Description);
            }
        }
        private async Task<bool> UsersInRoleExist(string roleName) {
            int usersInRole = await _userManager.Users.Where(user => user.DefaultRole.NormalizedName == roleName).CountAsync();
            //int usersInRole = await _userManager.Users.Where(user => _userManager.IsInRoleAsync(user, roleName).Result).CountAsync();
            return usersInRole > 0;
        }
    }
}

TicketingSystem/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketingSystem.Models;
using TicketingSystem.ViewModels;

namespace TicketingSystem.Controllers;
[Authorize]
public class UsersController : Controller {
    private UserManager<AppUser> _userManager;
    private RoleManager<AppRole> _roleManager;
    private ApplicationDbContext _appDbContext;
    private IPasswordHasher<AppUser> _passwordHasher;
    private IPasswordValidator<AppUser> _passwordValidator;


    public UsersController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, ApplicationDbContext appDbContext, IPasswordHasher<AppUser> passwordHasher, IPasswordValidator<AppUser> passwordValidator) {
        _userManager = userManager;
        _roleManager = roleManager;
        _appDbContext = appDbContext;
        _passwordHasher = passwordHasher;
        _passwordValidator = passwordValidator;
    }


    // GET: AppUsersController
    public async Task<IActionResult> Index() {
        var users = await GetAllUsersViewModel();
        return View(users);
    }

    // GET: AppUsersController/Create
    [Authorize(Roles = "ADMIN")]
    public async Task<IActionResult> CreateAsync() {

        await FillSelectsAsync();
        return View();
    }

    // POST: AppUsersController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAsync(AppUserViewModel appUserViewModel) {
        if (ModelState.IsValid) {
            AppUser newUser = new AppUser {
                UserName = appUserViewModel.UserName,
                Email = appUserViewModel.Email,
                PhoneNumber = appUserViewModel.PhoneNumber,
                DefaultRole = await _roleManager.Roles.FirstOrDefaultAsync(role => role.Id == appUserViewModel.DefaultRoleId),
                IsActive = true,
                CreateDate = DateTime.UtcNow,
                UpdateDate = DateTime.UtcNow
            };
            IdentityResult result = await _userManager.CreateAsync(newUser, appUserViewModel.Password);
            if (result.Succeeded) {
                IdentityResult resultAddToRole = await _userManager.AddToRoleAsync(newUser, newUser.DefaultRole.NormalizedName);
                if (resultAddToRole.Succeeded) {
                    return RedirectToAction("Index");
                }
                else {
                    ProcessErrors(resultAddToRole);
                }
            }
            else {
                ProcessErrors(result);
            }
        }
        await FillSelectsAsync();
        return View(appUserViewModel);
    }

    // GET: AppUsersController/Details/5
    public async Task<IActionResult> Details(string id) {
        if (id == null) {
            return View("NotFound");
        }
        var appUser = await _userManager.Users
            .Include(user => user.DefaultRole)
            .FirstOrDefaultAsync(user => user.Id == id);
        if (appUser == null) {
            return View("NotFound");
        }
        return View(ModelToViewModel(appUser));
    }


    // GET: AppUsersController/Edit/5
    public async Task<IActionResult> Edit(string id) {
        if (id == null) {
            return View("NotFound");
        }
        var appUser = await _userManager.FindByIdAsync(id);

        if (appUser == null) {
            return View("NotFound");
        }
        await FillSelectsAsync();
        return View(appUser);
    }

    // POST: AppUsersController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditAsync(string id, AppUser modifiedUser, string password) {
        AppUser userToEdit = await _userManager.FindByIdAsync(id);
        if (userToEdit == null) {
            ModelState.AddModelError("", "User not found.");
        }
        else if (!(userToEdit.ConcurrencyStamp).Equals(modifiedUser.ConcurrencyStamp)) {
            ModelState.AddModelError("", "User has been changed by a different instance, go back and try again.");
        }
        else if (!string.IsNullOrWhiteSpace(modifiedUser.Email) && !string.IsNullOrWhiteSpace(password)) {
            bool defaultRoleChanged = false;
            AppRole oldDefaultRole = await _roleManager.Roles.FirstOrDefaultAsync(role => role.Id == userToEdit.DefaultRoleId);
            AppRole newDefaultRole = await _roleManager.Roles.FirstOrDefaultAsync(role => role.Id == modifiedUser.DefaultRoleId);
            if (!(oldDefaultRole.NormalizedName).Equals(newDefaultRole.NormalizedName)) {
                userToEdit.DefaultRole = newDefaultRole;
                defaultRoleChanged = true;
            }
            userToEdit.IsActive = ((bool)modifiedUser.IsActive);
            userToEdit.Email = modifiedUser.Email;
            userToEdit.PhoneNumber = modifiedUser.PhoneNumber;
            userToEdit.UpdateDate = DateTime.UtcNow;
            IdentityResult validPassword = await _passwordValidator.ValidateAsync(_userManager, userToEdit, password);
            if (validPassword.Succeeded) {
                userToEdit.PasswordHash = _passwordHasher.HashPassword(userToEdit, password);
                IdentityResult identityResult = await _userManager.UpdateAsync(userToEdit);
                if (identityResult.Succeeded) {

                    if (defaultRoleChanged) {
                        IdentityResult resultRemoveFromRole = await _userManager.RemoveFromRoleAsync(userToEdit, oldDefaultRole.NormalizedName);
                        IdentityResult resultAddToRole = await _userManager.AddToRoleAsync(userToEdit, newDefaultRole.NormalizedName);
                        if (!resultRemoveFromRole.Succeeded) {
                            ProcessErrors(resultRemoveFromRole);
                        }
                        else if (!resultAddToRole.Succeeded) {
                            ProcessErrors(resultAddToRole);
                        }
                        else {
                            return RedirectToAction("Index");
                        }
                    }
                    return RedirectToAction("Index");
                }
                else {
                    ProcessErrors(identityResult);
                }
            }
            else {
                ProcessErrors(validPassword);
            }
        }
        await FillSelectsAsync();
        return View(userToEdit);
    }

    // GET: AppUsersController/Delete/5
    [Authorize(Roles = "ADMIN")]
    public async Task<IActionResult> Delete(string id) {
        if (id == null) {
            return View("NotFound");
        }
        var appUser = await _userManager.FindByIdAsync(id);
        if (appUser == null) {
            return View("NotFound");
        }
        return View(appUser);
    }

    // POST: AppUsersController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteAsync(string id) {
        var appUser = await _userManager.FindByIdAsync(id);
        if (appUser == null) {
            ModelState.AddModelError("", "User not found.");
            return View(appUser);
        }
        else if (appUser.IsActive) {
            ModelState.AddModelError("", "User is still active, deactivate the user first.");
            return View(appUser);
        }
        else {
            IdentityResult result = await _userManager.DeleteAsync(appUser);
            if (result.Succeeded) {
                return RedirectToAction(nameof(Index));
            }
            else {
                ProcessErrors(result);
            }
        }
        return View("Index", _userManager.Users);
    }

    private void ProcessErrors(IdentityResult identityResult) {
        foreach (var error in identityResult.Errors) {
            ModelState.AddModelError("", error.Description);
        }
    }
    public async Task<RoleDropdownViewModel> GetRoleDropdownsData() {
        AppUser appUser = await _userManager.Users.FirstOrDefaultAsync(user => user.Id == _userManager.GetUserId(User));
        AppRole appRole = await _roleManager.Roles.FirstOrDefaultAsync(role => role.Id == appUser.DefaultRoleId);
        string appUserDefaultRole = appRole.NormalizedName;
        var rolesDropDownData = new RoleDropdownViewModel();
        if (appUserDefaultRole == "ADMIN") {
            rolesDropDownData = new RoleDropdownViewModel() {
                Roles = await _roleManager.Roles
                .Where(role => role.IsActive == true)
                .OrderBy(role => role.NormalizedName)
                .ToListAsync()
            };
        }
        else {
            rolesDropDownData = new RoleDropdownViewModel() {
                Roles = await _roleManager.Roles
                .Where(role => role.IsActive == true)
                .Where(role => role.Id == appRole.Id)
                .ToListAsync()
            };
        }
        return rolesDropDownData;
    }

    private async Task FillSelectsAsync() {
        var rolesDropDownData = await GetRoleDropdownsData();
        ViewBag.RolesDropDownData = new SelectList(rolesDropDownData.Roles, "Id", "NormalizedName");
    }

    public async Task<IEnumerable<AppUserViewModel>> GetAllUsersViewModel() {
        List<AppUser> users = await _userManager.Users
            .Include(user => user.DefaultRole)
            .OrderBy(user => user.NormalizedUserName)
            .OrderBy(user => user.DefaultRole.NormalizedName)
            .ToListAsync();
        List<AppUserViewModel> usersViewModel = new List<AppUserViewModel>();
        foreach (var user in users) {
            usersViewModel.Add(ModelToViewModel(user));
        }
        usersViewModel
            .OrderBy(user => user.DefaultRoleId)
            .OrderBy(user => user.NormalizedUserName);
        return usersViewModel;
    }

    public AppUserViewModel ModelToViewModel(AppUser user) {
        return new AppUserViewModel {

TicketingSystem/Views/Shared/AccessDenied.cshtml
@model string
@{
    ViewData["Title"] = "Access Denied";
}
<h1 class="text-danger">@ViewData["Title"]</h1>
<p>You were not authorised to view this content!</p>
<a asp-controller="Home" asp-action="Index" class="btn btn-secondary my-2">Back</a>
@if (User?.Identity?.IsAuthenticated ?? false) {
    <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
}

TicketingSystem/Views/Shared/NotFound.cshtml
@model string
@{
    ViewData["Title"] = "Page Not Found";
}
<h1 class="text-danger">@ViewData["Title"]</h1>
<p>The page you are trying to access was not found!</p>
<a asp-action="Index" class="btn btn-secondary my-2">Back</a>

TicketingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - jirkuc simpleTicketS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TicketingSystem.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" asp-append-version="true" />

</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    jirkuc
                    <img src="~/img/stickets.svg" alt="jirkuc simpleTicketS logo" width="32" height="32" />
                    simpleTicketS
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>
                        @if (User.Identity.IsAuthenticated) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            @if (User.IsInRole("ADMIN")) {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                                </li>
                            }
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated) {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a href="@Url.Action("Create","Tickets")" class="btn btn-success btn-sm text-light overflow-hidden my-2 me-3" style="min-width: 100px">Create Ticket</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Tickets" asp-action="Details" method="get" class="d-flex input-group-sm my-2 me-3" role="search">
                                    <input name="id" class="form-control me-2" type="search" placeholder="Ticket number" aria-label="Search" style="min-width: 120px; max-width: 150px" />
                                    <button class="btn btn-outline-success" type="submit">Search</button>
                                </form>
                            </li>

                        </ul>
                    }
                    @if (User?.Identity?.IsAuthenticated ?? false) {
                        <div class="nav-item mt-2 mb-1 me-2 text-sm-center">
                            User: <strong> @User.Identity.Name </strong>
                        </div>
                        <div>
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger btn-sm my-1">Logout</a>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <main class="mt-5 pt-5">
        <div class="container-fluid px-5">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </main>

    <footer class="border-top footer text-muted">
        <div class="container text-secondary">
            &copy; 2024 - <a href="mailto:jirkuc[at]gmail.com" class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">jirkuc</a> SimplE Ticketing Management System - <a asp-area="" asp-controller="Home" asp-action="Help">Help</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>